# # #

name: tmlmobilidade-bridge

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  bridgedb:
    image: postgres:alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    ports:
      - 37014:5432
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      - POSTGRES_DB=$BRIDGEDB_DB
      - POSTGRES_USER=$BRIDGEDB_USER
      - POSTGRES_PASSWORD=$BRIDGEDB_PASSWORD
    env_file:
      - ./.env