/**
 * This file is auto-generated by the generate-sql-registry.sh script.
 * Do not edit this file manually. Run `npm run repo:sql` to regenerate.
 *
 * Source: every .sql file under modules/<module>/sql
 */

/* * */

export const SQL_FILES = {
	hub: [
		'eta/bootstrap/create-tables.sql',
		'eta/bootstrap/mv-predict-node-etas.sql',
		'eta/bootstrap/mv-predict-trip-stop-etas.sql',
		'eta/bootstrap/mv-sync-curr-vehicle-events.sql',
		'eta/cleanup/1-delete-out-of-window-curr-rides.sql',
		'eta/cleanup/2-delete-out-of-window-curr-vehicle-events.sql',
		'eta/cleanup/3-delete-orphan-curr-waypoints.sql',
		'eta/cleanup/4-delete-out-of-window-hist-rides.sql',
		'eta/cleanup/5-delete-orphan-hist-vehicle-events.sql',
		'eta/cleanup/6-delete-orphan-hist-node-travel-times.sql',
		'eta/cleanup/7-delete-out-of-window-hist-node-travel-times-aggregation.sql',
		'eta/loader/aggregate-hist-node-travel-times.sql',
		'eta/loader/build-hist-node-travel-times.sql',
		'eta/loader/load-current-waypoints.sql',
		'eta/loader/load-historical-vehicle-events.sql',
		'eta/loader/load-rides.sql',
		'eta/loader/snap-waypoints.sql',
		'publish-realtime/select-eta-by-stop-gtfs.sql',
		'publish-realtime/select-eta-by-stop.sql',
		'publish-realtime/select-eta-by-trip-gtfs.sql',
		'publish-realtime/select-eta-by-trip.sql',
		'publish-realtime/select-eta-gtfs.sql',
		'publish-realtime/select-eta.sql',
		'publish-realtime/select-vehicle-positions.sql',
		'publish-vehicles/select-vehicle-positions.sql',
	],
	operation: [
		'alerts/list-lines.sql',
		'alerts/list-rides.sql',
		'alerts/list-stops.sql',
		'compose-alert/fetch-lines-reference-context.sql',
		'compose-alert/fetch-rides-reference-context.sql',
		'compose-alert/fetch-stops-reference-context.sql',
		'rides/get-ride.sql',
		'rides/list-rides.sql',
	],
	performance: [
		'demand/by-agency-by-operational-date.sql',
	],
	tracker: [
		'pt-tml-fertagus-rawdb-stream/find-trip-id.sql',
		'pt-tml-ml-api-fetch/find-hashed-shape.sql',
		'pt-tml-ml-api-fetch/find-hashed-trip.sql',
		'pt-tml-ml-api-fetch/find-rides-for-train.sql',
	],
} as const;
