import type { Metadata } from 'next';

import { MantineProvider } from '@mantine/core';

import './globals.css';

import '@mantine/core/styles.css';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono',
});

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<MantineProvider>
					{children}
				</MantineProvider>
			</body>
		</html>
	);
}
