#!/bin/bash

# Script to generate the SQL registry from the module structure.
# Usage: ./generate-sql-registry.sh [--check] [output_file]
#
# Scans `modules/<module>/sql/**/*.sql` and emits a typed registry consumed by
# `sqlPath()` in @tmlmobilidade/go-utils-sql. With `--check` nothing is written:
# the script exits non-zero when the committed registry is out of date.

set -e

CHECK_ONLY=false
if [ "$1" = "--check" ]; then
    CHECK_ONLY=true
    shift
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Go up one level from scripts/ to the project root
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MODULES_DIR="${PROJECT_ROOT}/modules"
OUTPUT_FILE="${1:-${PROJECT_ROOT}/packages-new/utils/sql/src/registry.generated.ts}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

TEMP_FILE=$(mktemp)
trap "rm -f ${TEMP_FILE}" EXIT

if [ "${CHECK_ONLY}" = false ]; then
    printf "${GREEN}Generating SQL registry from module structure...${NC}\n"
fi

# Emit an object key, quoting it only when it is not a bare identifier.
emit_key() {
    case "$1" in
        [A-Za-z_$]*[!A-Za-z0-9_$]*) printf "'%s'" "$1" ;;
        [A-Za-z_$]*)                printf "%s" "$1" ;;
        *)                          printf "'%s'" "$1" ;;
    esac
}

{
    printf "/**\n"
    printf " * This file is auto-generated by the generate-sql-registry.sh script.\n"
    printf " * Do not edit this file manually. Run \`npm run repo:sql\` to regenerate.\n"
    printf " *\n"
    printf " * Source: every .sql file under modules/<module>/sql\n"
    printf " */\n"
    printf "\n"
    printf "/* * */\n"
    printf "\n"
    printf "export const SQL_FILES = {\n"
} > "${TEMP_FILE}"

MODULE_COUNT=0
FILE_COUNT=0

for MODULE_PATH in "${MODULES_DIR}"/*; do
    [ -d "${MODULE_PATH}" ] || continue

    MODULE_NAME="$(basename "${MODULE_PATH}")"
    SQL_DIR="${MODULE_PATH}/sql"

    [ -d "${SQL_DIR}" ] || continue

    SQL_FILES="$(cd "${SQL_DIR}" && find . -type f -name '*.sql' | sed 's|^\./||' | LC_ALL=C sort)"

    if [ -z "${SQL_FILES}" ]; then
        if [ "${CHECK_ONLY}" = false ]; then
            printf "${YELLOW}  ${MODULE_NAME}: no .sql files, skipping${NC}\n"
        fi
        continue
    fi

    MODULE_COUNT=$((MODULE_COUNT + 1))

    {
        printf "\t"
        emit_key "${MODULE_NAME}"
        printf ": [\n"
    } >> "${TEMP_FILE}"

    MODULE_FILE_COUNT=0
    while IFS= read -r SQL_FILE; do
        printf "\t\t'%s',\n" "${SQL_FILE}" >> "${TEMP_FILE}"
        MODULE_FILE_COUNT=$((MODULE_FILE_COUNT + 1))
    done <<< "${SQL_FILES}"

    FILE_COUNT=$((FILE_COUNT + MODULE_FILE_COUNT))

    printf "\t],\n" >> "${TEMP_FILE}"

    if [ "${CHECK_ONLY}" = false ]; then
        printf "${GREEN}  ${MODULE_NAME}: ${MODULE_FILE_COUNT} file(s)${NC}\n"
    fi
done

printf "} as const;\n" >> "${TEMP_FILE}"

if [ "${MODULE_COUNT}" -eq 0 ]; then
    printf "${RED}No modules/<module>/sql directories found under ${MODULES_DIR}${NC}\n" >&2
    exit 1
fi

if [ "${CHECK_ONLY}" = true ]; then
    if [ ! -f "${OUTPUT_FILE}" ] || ! diff -q "${TEMP_FILE}" "${OUTPUT_FILE}" > /dev/null; then
        printf "${RED}SQL registry is out of date. Run \`npm run repo:sql\` and commit the result.${NC}\n" >&2
        [ -f "${OUTPUT_FILE}" ] && diff -u "${OUTPUT_FILE}" "${TEMP_FILE}" >&2 || true
        exit 1
    fi
    printf "${GREEN}SQL registry is up to date.${NC}\n"
    exit 0
fi

mkdir -p "$(dirname "${OUTPUT_FILE}")"
cp "${TEMP_FILE}" "${OUTPUT_FILE}"

printf "${GREEN}Wrote ${FILE_COUNT} file(s) across ${MODULE_COUNT} module(s) to ${OUTPUT_FILE}${NC}\n"
